# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxT41nq_fpmlp2YrzW-9NDrYPKajFerW
"""

from fastapi import FastAPI
from pydantic import BaseModel
import numpy as np
import joblib

# -----------------------------------
# Load trained model & scaler
# -----------------------------------
model = joblib.load("risk_model.pkl")
scaler = joblib.load("scaler.pkl")

# -----------------------------------
# Initialize FastAPI
# -----------------------------------
app = FastAPI(
    title="Breast Cancer Risk Prediction API",
    description="Predict cancer risk and screening decision",
    version="1.0"
)

# -----------------------------------
# Input schema
# -----------------------------------
class PatientInput(BaseModel):
    features: list  # 30 numeric features


# -----------------------------------
# Business thresholds (optimization logic)
# -----------------------------------
HIGH_RISK = 0.60
VERY_HIGH_RISK = 0.85


# -----------------------------------
# Prediction Endpoint
# -----------------------------------
@app.post("/predict")
def predict_risk(data: PatientInput):

    # Convert input to array
    X = np.array(data.features).reshape(1, -1)

    # Scale features
    X_scaled = scaler.transform(X)

    # Predict probability
    cancer_risk = model.predict_proba(X_scaled)[0][1]

    # Optimization-style decision
    if cancer_risk >= VERY_HIGH_RISK:
        decision = "MANDATORY_SCREENING"
    elif cancer_risk >= HIGH_RISK:
        decision = "RECOMMENDED_SCREENING"
    else:
        decision = "NO_ADVANCED_SCREENING"

    return {
        "cancer_risk_probability": round(float(cancer_risk), 4),
        "screening_decision": decision
    }